############################
## CHANGE THESE
############################

baseURL: "https://Tirexxploner.github.io/qubt"
title: qubt

############################
## MISC
############################

enableEmoji: true
disableKinds: ["taxonomy", "term"]
languageCode: "en-us"
enableRobotsTXT: true
